version: "3"

services:
  oba_bundler:
    build: ./bundler
    volumes:
      - ./bundle:/bundle
    environment:
      - GTFS_URL

  oba_database_mysql:
    image: mysql:8.3
    container_name: oba_database_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ins3cure!
      MYSQL_DATABASE: oba_database
      MYSQL_USER: oba_user
      MYSQL_PASSWORD: oba_password
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    restart: always
  
  oba_database_postgres:
    image: postgres:13
    container_name: oba_database_postgres
    environment:
      POSTGRES_DB: oba_database
      POSTGRES_USER: oba_user
      POSTGRES_PASSWORD: oba_password
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    restart: always

  oba_app:
    container_name: oba_app
    depends_on:
      - oba_database_postgres
    build: ./oba
    environment:
      - JDBC_URL=jdbc:postgresql://oba_database_postgres:5432/oba_database
      - JDBC_USER=oba_user
      - JDBC_PASSWORD=oba_password
    volumes:
      # Share the host's `bundle` directory
      # with the filesystem of the OBA service.
      - ./bundle:/bundle
    ports:
      # Access the webapp on your host machine at a path like
      # http://localhost:8080/onebusaway-api-webapp/api/where/agency/${YOUR_AGENCY}.json?key=TEST
      - "8080:8080"
    # restart: always

volumes:
  mysql-data:
  postgres-data: